sudo: false
language: node_js
node_js:
- '0.12'
- 4
- 5
after_success: npm run report-cov
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: EY1je9WLB7uQl4kScsprpTLfBFAbuqYWcYR6t2FB9ZArZYCD0jIeLjJg1wzVW+YkHdr4ZOguUyh2SQdbMe4a+Y6KD2xjTwKFJyL5KB9a1t31i5kAHQxc7lxbCnpBSXVcwegCsSg2tk6dhde6xOQDkW72j/OkcLGjVRNR/qYUsA9n7UtvgQaFVkrDfLNJhinKGgD1IFd6ZZT6/FqpNGrX9v3z1cB9M+ZWoHZdTz3OzVK+1Wa7kvxhofHKqDiSxsn6F9AIsHFIqs2UsScihFhhMEuI+z7YEUu3XQ4qkenvJ26KuIwMMqBFtXtWWs1Dyid3ra4Mpy9g0xHaNI9Ipn2SrjbKuWunB83ei/ynqVev90ev0qslk3gcSTCOdEn1Wkb4xjzyMGlzgoSCw1dF/YPOxGLODqfoQTydeRrm/vIVYiqwOp9s03hM3SouckY1IqWx6k3MqKXkPuNh3ar+TurBwft8h3TfBLz/twnLfrUi5SKa3+2OdVaulr9B4/6jIVffyhEFYZ1VHRvCYSlX0fVtOSjakNBtUMG6upMzmCj6eZQAJ9ZrOuzeGsEP7FdjAEZyPWxplq5+Z29UkQbAKf9THnJHbjW2uASqUfqrKhJSMlB3pONkm2rABLOPxT4zO/Qs43hbVib/NoNrepsKjs57KV7mBav0Zedl320iLfOMdio=
  on:
    all_branches: true
    tags: true
    repo: Brightspace/node-jwk-to-pem
