sudo: false
language: node_js
node_js:
  - '0.12'
  - 4
  - 6
  - 8
  - 10
  - 11
after_success: npm run report-cov
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 94d3......8807
    secure: G85ice0iqGW3Z3ZKYUmqwXROEZP34TLFrP1L4bdVdEZd5RLTH7WydSd2SQBKNVqWkhxSKSIvigt8Ww8mUoNP7PBKpS7av3sGDH0FtOyLfp73aXnRikT/dvozvneyU4W10Rgty3O2JRtZ+B8PR2EbktOUgorVjMZTmXOck7GgCUXDxCVUurRX6scNrvO5chJU6nTWdH36WGMbuKdkfueGFSkiU4+AU03ZlCkJWDh2NNxR/Sg5Hstv6jKPomf9YHO6ZYQAZ3qlrPJjs2mkpVNBafqmpgGMxceR/apFNP/PLQ8BLu0hw1aKetJZvjSyhlT17Lurv918QL4pdTvo8WKzkRPGz1ZTWN26LH6vc5d67RULFenNgdlXDvfJe3POJqnrkj8G1TSOUyiCyGsAICNRKAuzMECrYEhh/55jO2X9qn6TR3LUJtQPK6f5eneMEBib38AFwFxEyRq8zZyCt/oZI7vys1FkOIHoOjDy2NgmyQjbfa6LjteJYX5LAlXn1AHUoO3VntXlz3PBms/3+rZEan63GTdsY6crEZ543ou2vsDhAGsy6ALn9oL/iF6KVQKPFDlMcQ55hjvyd+q/gcZgBh5LtiEZX9RbC6rYpDUTC0Zs57QeW1ODELxPfIQHihMZGKxG4NBFMUR9aV0tZqVrOHB6dFpEIARESfCTTTu90Ag=
  on:
    all_branches: true
    tags: true
    repo: Brightspace/node-jwk-to-pem
    node: 10
