on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        node: [8, 10, 12, 14, 16, 18, 20]
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout

      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm test
